import {
  type FitnessTrendData,
  type TaperWeek,
  type TrendBand,
  type TrendDay,
} from "../types";

/**
 * Twelve weeks of a real performance-management chart, generated by running
 * the server's `buildFitnessTrend` over a scripted block (base build → a hard
 * three-week block → a recovery week → a final overload) and mapping it with
 * `mapFitnessTrendApp`. Handwritten CTL/ATL curves cannot be trusted: the
 * decay constants tie every day to the days before it, and a plausible-looking
 * invented series charts a shape the model can never produce.
 *
 * It exercises everything the chart draws: deep-fatigue and steep-ramp bands,
 * a live flag, deeply negative current form, and a feasible taper.
 */
const SERIES_START = "2026-03-31";

/** [load, ctl, atl, tsb] per consecutive day from SERIES_START. */
const SERIES_ROWS: [number, number, number, number][] = [
  [0, 0, 0, 0],
  [55, 1.3, 7.3, -6],
  [0, 1.3, 6.3, -5.1],
  [40, 2.2, 10.8, -8.7],
  [95, 4.4, 22, -17.7],
  [0, 4.3, 19.1, -14.8],
  [55, 5.5, 23.9, -18.4],
  [0, 5.3, 20.7, -15.4],
  [55, 6.5, 25.3, -18.8],
  [0, 6.3, 21.9, -15.6],
  [40, 7.1, 24.3, -17.2],
  [95, 9.2, 33.7, -24.5],
  [0, 9, 29.2, -20.3],
  [55, 10.1, 32.7, -22.6],
  [0, 9.8, 28.3, -18.5],
  [55, 10.9, 31.9, -21],
  [0, 10.6, 27.6, -17],
  [40, 11.3, 29.3, -17.9],
  [95, 13.3, 38, -24.7],
  [0, 13, 33, -20],
  [55, 14, 35.9, -21.9],
  [0, 13.6, 31.1, -17.5],
  [55, 14.6, 34.3, -19.7],
  [0, 14.3, 29.7, -15.5],
  [40, 14.9, 31.1, -16.2],
  [95, 16.8, 39.6, -22.8],
  [0, 16.4, 34.3, -18],
  [55, 17.3, 37.1, -19.8],
  [0, 16.9, 32.1, -15.3],
  [55, 17.8, 35.2, -17.4],
  [0, 17.3, 30.5, -13.2],
  [40, 17.9, 31.8, -13.9],
  [95, 19.7, 40.2, -20.5],
  [0, 19.2, 34.8, -15.6],
  [55, 20.1, 37.5, -17.4],
  [0, 19.6, 32.5, -12.9],
  [55, 20.4, 35.5, -15.1],
  [0, 20, 30.8, -10.8],
  [40, 20.4, 32, -11.6],
  [95, 22.2, 40.4, -18.2],
  [0, 21.7, 35, -13.4],
  [55, 22.4, 37.7, -15.2],
  [0, 21.9, 32.7, -10.8],
  [116, 24.1, 43.8, -19.6],
  [0, 23.6, 37.9, -14.4],
  [84, 25, 44.1, -19.1],
  [200, 29.1, 64.8, -35.7],
  [0, 28.4, 56.2, -27.8],
  [116, 30.5, 64.2, -33.7],
  [0, 29.8, 55.6, -25.9],
  [116, 31.8, 63.7, -31.9],
  [0, 31, 55.2, -24.1],
  [84, 32.3, 59, -26.7],
  [200, 36.2, 77.8, -41.6],
  [0, 35.4, 67.4, -32.1],
  [116, 37.3, 73.9, -36.6],
  [0, 36.4, 64.1, -27.7],
  [116, 38.3, 71, -32.7],
  [0, 37.4, 61.5, -24.2],
  [84, 38.5, 64.5, -26],
  [200, 42.3, 82.6, -40.3],
  [0, 41.3, 71.6, -30.3],
  [116, 43, 77.5, -34.4],
  [0, 42, 67.2, -25.1],
  [25, 41.6, 61.6, -19.9],
  [0, 40.6, 53.4, -12.7],
  [18, 40.1, 48.7, -8.5],
  [43, 40.2, 47.9, -7.7],
  [0, 39.2, 41.5, -2.3],
  [25, 38.9, 39.3, -0.4],
  [0, 38, 34.1, 3.9],
  [55, 38.4, 36.9, 1.5],
  [0, 37.5, 32, 5.5],
  [40, 37.5, 33, 4.5],
  [95, 38.9, 41.3, -2.4],
  [0, 38, 35.8, 2.2],
  [55, 38.4, 38.3, 0],
  [0, 37.5, 33.2, 4.2],
  [121, 39.4, 44.9, -5.5],
  [0, 38.5, 38.9, -0.4],
  [88, 39.7, 45.5, -5.8],
  [209, 43.7, 67.2, -23.6],
  [0, 42.6, 58.3, -15.7],
  [121, 44.5, 66.6, -22.2],
  [0, 43.4, 57.8, -14.3],
  [121, 45.3, 66.2, -20.9],
  [0, 44.2, 57.4, -13.2],
  [88, 45.2, 61.5, -16.2],
  [209, 49.1, 81.1, -32],
  [0, 47.9, 70.3, -22.4],
];

/** Rest projection past the last recorded day, same encoding. */
const PROJECTION_ROWS: [number, number, number, number][] = [
  [0, 46.8, 60.9, -14.1],
  [0, 45.7, 52.8, -7.1],
  [0, 44.6, 45.8, -1.2],
  [0, 43.6, 39.7, 3.9],
  [0, 42.5, 34.4, 8.1],
  [0, 41.5, 29.8, 11.7],
  [0, 40.6, 25.9, 14.7],
  [0, 39.6, 22.4, 17.2],
  [0, 38.7, 19.4, 19.2],
  [0, 37.8, 16.8, 20.9],
  [0, 36.9, 14.6, 22.3],
  [0, 36, 12.7, 23.3],
  [0, 35.2, 11, 24.2],
  [0, 34.3, 9.5, 24.8],
];

/** Taper-plan days, same encoding. */
const TAPER_ROWS: [number, number, number, number][] = [
  [42.2, 47.8, 66.6, -18.8],
  [42.2, 47.7, 63.3, -15.7],
  [42.2, 47.5, 60.5, -13],
  [42.2, 47.4, 58.1, -10.7],
  [42.2, 47.3, 55.9, -8.7],
  [42.2, 47.2, 54.1, -7],
  [42.2, 47, 52.5, -5.5],
  [31.6, 46.7, 49.7, -3.1],
  [31.6, 46.3, 47.3, -1],
  [31.6, 46, 45.2, 0.7],
  [31.6, 45.6, 43.4, 2.2],
  [31.6, 45.3, 41.8, 3.5],
  [31.6, 45, 40.5, 4.5],
  [31.6, 44.7, 39.3, 5.4],
  [23.7, 44.2, 37.2, 6.9],
  [23.7, 43.7, 35.4, 8.3],
  [23.7, 43.2, 33.9, 9.4],
  [23.7, 42.8, 32.5, 10.2],
  [23.7, 42.3, 31.3, 11],
  [23.7, 41.9, 30.3, 11.5],
  [23.7, 41.5, 29.5, 12],
];

function addDays(iso: string, days: number): string {
  const date = new Date(`${iso}T00:00:00Z`);
  date.setUTCDate(date.getUTCDate() + days);
  return date.toISOString().split("T")[0]!;
}

function toDays(
  rows: [number, number, number, number][],
  startDate: string,
): TrendDay[] {
  return rows.map(([load, ctl, atl, tsb], index) => ({
    date: addDays(startDate, index),
    load,
    ctl,
    atl,
    tsb,
  }));
}

export const mockSeries: TrendDay[] = toDays(SERIES_ROWS, SERIES_START);

const forwardStart = addDays(SERIES_START, SERIES_ROWS.length);
export const mockProjection: TrendDay[] = toDays(PROJECTION_ROWS, forwardStart);
export const mockTaperDays: TrendDay[] = toDays(TAPER_ROWS, forwardStart);

export const mockBands: TrendBand[] = [
  {
    kind: "deep-fatigue",
    startDate: "2026-05-16",
    endDate: "2026-05-20",
    days: 5,
    reason:
      "TSB at or below -25 for 5 consecutive days — deep fatigue; an easy block or rest is overdue.",
  },
  {
    kind: "deep-fatigue",
    startDate: "2026-05-22",
    endDate: "2026-05-27",
    days: 6,
    reason:
      "TSB at or below -25 for 6 consecutive days — deep fatigue; an easy block or rest is overdue.",
  },
  {
    kind: "deep-fatigue",
    startDate: "2026-05-29",
    endDate: "2026-06-02",
    days: 5,
    reason:
      "TSB at or below -25 for 5 consecutive days — deep fatigue; an easy block or rest is overdue.",
  },
  {
    kind: "steep-ramp",
    startDate: "2026-04-07",
    endDate: "2026-04-09",
    days: 3,
    reason:
      "CTL climbed 5 in the last 7 days — a steep ramp; sustained rates above ~5/week carry injury and illness risk.",
  },
  {
    kind: "steep-ramp",
    startDate: "2026-05-16",
    endDate: "2026-06-02",
    days: 18,
    reason:
      "CTL climbed 5.6 in the last 7 days — a steep ramp; sustained rates above ~5/week carry injury and illness risk.",
  },
  {
    kind: "steep-ramp",
    startDate: "2026-06-22",
    endDate: "2026-06-28",
    days: 7,
    reason:
      "CTL climbed 5.3 in the last 7 days — a steep ramp; sustained rates above ~5/week carry injury and illness risk.",
  },
];

export const mockTaperWeeks: TaperWeek[] = [
  {
    week: 1,
    startDate: "2026-06-29",
    endDate: "2026-07-05",
    days: 7,
    dailyLoad: 42.2,
    weekLoad: 295.1,
    pctOfRecent: 83,
  },
  {
    week: 2,
    startDate: "2026-07-06",
    endDate: "2026-07-12",
    days: 7,
    dailyLoad: 31.6,
    weekLoad: 221.4,
    pctOfRecent: 62,
  },
  {
    week: 3,
    startDate: "2026-07-13",
    endDate: "2026-07-19",
    days: 7,
    dailyLoad: 23.7,
    weekLoad: 166,
    pctOfRecent: 47,
  },
];

const mockFlags: string[] = [
  "CTL climbed 5.3 in the last 7 days — a steep ramp; sustained rates above ~5/week carry injury and illness risk.",
];

/** The default payload: recorded series plus a solved taper. */
export const mockFitnessTrendData: FitnessTrendData = {
  days: 90,
  series: mockSeries,
  projection: mockProjection,
  taper: {
    targetDate: "2026-07-19",
    targetTsb: 12,
    achievedTsb: 12,
    feasible: true,
    note: null,
    weeks: mockTaperWeeks,
    days: mockTaperDays,
    totalLoad: 682.5,
    recentDailyLoad: 51,
  },
  current: mockSeries[mockSeries.length - 1]!,
  tsbPositiveDate: "2026-07-02",
  bands: mockBands,
  flags: mockFlags,
  activitiesIncluded: 51,
  activitiesMissingLoad: 0,
};

/** No target date: the forward half is a zero-load rest projection. */
export const mockRestProjectionData: FitnessTrendData = {
  ...mockFitnessTrendData,
  taper: null,
  tsbPositiveDate: "2026-07-02",
};

/**
 * A window whose activities carried no heart rate: 90 zero-load days. Row
 * count alone would pass; the chart has nothing to draw.
 */
export const mockNoLoadData: FitnessTrendData = {
  ...mockFitnessTrendData,
  series: mockSeries.map((day) => ({
    ...day,
    load: 0,
    ctl: 0,
    atl: 0,
    tsb: 0,
  })),
  projection: [],
  taper: null,
  current: { date: "2026-06-28", load: 0, ctl: 0, atl: 0, tsb: 0 },
  tsbPositiveDate: null,
  bands: [],
  flags: [],
  activitiesIncluded: 12,
  activitiesMissingLoad: 12,
};
